### ISSUE TITLE
能否分享一下MutatingWebhookConfiguration文件？

### ISSUE THREAD

**Issue by gdzy1987** [zwwhdls/KubeAdmissionWebhookDemo#1]

**Comment by zwwhdls** [comment]
@gdzy1987 代码和文章里都有写哦，将代码里生成的 yaml 文件按照文章所述修改即可：

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
  caBundle: LS0tLS1CRUdJTiBDRVJ...FLS0tLS0=
  url: https://<server_ip>:9443/mutate-app-o0w0o-cn-v1-app
  failurePolicy: Fail
  name: mapp.kb.io
  rules:
  - apiGroups:
    - app.o0w0o.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
```
